sudo: false

language: python

python:
 - "3.5"

jobs:
  include:
  - stage: tests
    env: HAZARDLIB
    script:
        - nosetests --with-doctest -xvs -a'!slow' openquake.baselib
        - nosetests --with-doctest -xvs -a'!slow' openquake.hazardlib
        - nosetests --with-doctest -xvs -a'!slow' openquake.hmtk
  - stage: tests
    env: ENGINE
    before_script:
        - mkdir ~/oqdata
    script:
        - nosetests --with-doctest -xvs -a'!slow' openquake.engine
        - nosetests --with-doctest -xvs -a'!slow' openquake.server
        - nosetests --with-doctest -xvs -a'!slow' openquake.calculators
        - nosetests --with-doctest -xvs -a'!slow' openquake.risklib
        - nosetests --with-doctest -xvs -a'!slow' openquake.commonlib
        - nosetests --with-doctest -xvs -a'!slow' openquake.commands
        - bin/oq webui migrate
        - cat /tmp/webui*
    after_success:
        - pip install sphinx==1.3.6 && cd doc/sphinx && make html
  - stage: tests
    env: DEMOS
    script: 
        - bin/run-demos.sh

install:
  - pip -q install -r requirements-py35-linux64.txt
  - pip -q install -e .

before_script:
  - python -c'import platform; print(platform.platform())'

after_script:
  - bin/oq reset --yes
