sudo: false

language: python

python:
 - "3.6"

addons:
  apt:
    packages:
    - git
    - libspatialindex-dev

install:
  - if [ "$(git ls-remote --heads https://github.com/gem/oq-hazardlib.git ${TRAVIS_BRANCH})" != "" ]; then BRANCH=$TRAVIS_BRANCH; else BRANCH='master'; fi; git clone -b ${BRANCH} --depth=1 https://github.com/gem/oq-hazardlib.git && echo "Running on oq-hazardlib/${BRANCH}"
  - pip install -e oq-hazardlib/
  - pip install -e .[rtree,celery]

script:
  - nosetests --with-doctest -vs -a'!slow'
  - cat /tmp/webui*
  - bin/oq info -r demos/hazard
  - bin/oq reset --yes
